import React, { useState, useEffect } from 'react';
import { FileText, ArrowRight, ShieldCheck, ShieldAlert, Calendar, LayoutGrid, Terminal } from 'lucide-react';

export default function ReportList({ setActiveTab, setActiveReportId }) {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await fetch('/api/audits');
      const data = await res.ok ? await res.json() : [];
      setReports(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const getRiskColor = (risk) => {
    switch (risk) {
      case 'GREEN': return 'border-emerald-500/20 text-emerald-400 bg-emerald-500/5';
      case 'AMBER': return 'border-amber-500/20 text-amber-400 bg-amber-500/5';
      case 'RED': return 'border-rose-500/20 text-rose-400 bg-rose-500/5';
      default: return 'border-slate-800 text-slate-400 bg-slate-900';
    }
  };

  const handleViewReport = (id) => {
    setActiveReportId(id);
    setActiveTab('auditor');
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Description */}
      <div className="p-4 rounded-xl glass-panel border border-slate-800 flex items-center gap-3">
        <div className="h-9 w-9 rounded-lg bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center">
          <FileText className="h-5 w-5 text-indigo-400" />
        </div>
        <div>
          <h3 className="font-bold text-sm text-white">Compliance Audit Records</h3>
          <p className="text-xs text-slate-400">Review historical audits and code diff improvements generated by ComplianceAgent AI.</p>
        </div>
      </div>

      {loading ? (
        <div className="h-48 flex items-center justify-center text-xs text-slate-500">
          Loading historical reports...
        </div>
      ) : reports.length === 0 ? (
        <div className="p-8 text-center bg-slate-900 border border-slate-800 rounded-2xl max-w-sm mx-auto">
          <ShieldCheck className="h-10 w-10 text-emerald-500/30 mx-auto mb-3" />
          <h4 className="text-sm font-semibold text-white">No Audits Recorded</h4>
          <p className="text-xs text-slate-500 mt-1 max-w-xs leading-normal">
            No source code audits have been processed yet. Navigate to the AI Code Auditor tab to execute your first compliance check.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {reports.map((report) => (
            <div 
              key={report.id}
              className="p-6 rounded-2xl glass-panel border border-slate-800 hover:border-slate-700 transition-all flex flex-col justify-between"
            >
              <div>
                {/* Meta details */}
                <div className="flex justify-between items-start gap-4">
                  <div>
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Target Audit File</span>
                    <h4 className="font-bold text-sm text-white mt-0.5 truncate max-w-[200px]">
                      {report.repo_path || 'Unnamed Code Snippet'}
                    </h4>
                  </div>
                  
                  <div className="flex flex-col items-end gap-1">
                    <span className="text-[10px] text-slate-500 flex items-center gap-1">
                      <Calendar className="h-3 w-3" /> {new Date(report.created_at).toLocaleDateString()}
                    </span>
                    <span className="text-[9px] text-slate-600">
                      {new Date(report.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                </div>

                {/* Score section */}
                <div className="my-5 flex items-center gap-4">
                  <div className="text-3xl font-extrabold text-white tracking-tight">
                    {report.score}<span className="text-xs font-semibold text-slate-500">/100</span>
                  </div>
                  <div className={`px-3 py-1 rounded-lg border text-[10px] font-bold uppercase tracking-wider ${getRiskColor(report.risk_level)}`}>
                    {report.risk_level} Status
                  </div>
                </div>

                {/* Issues preview counts */}
                <div className="space-y-2 border-t border-slate-800/60 pt-4 text-xs">
                  <div className="flex justify-between text-slate-400">
                    <span>Performance Regressions:</span>
                    <span className="font-semibold text-slate-200">{report.issues.length}</span>
                  </div>
                  <div className="flex justify-between text-slate-400">
                    <span>Available Code Fixes:</span>
                    <span className="font-semibold text-slate-200">{report.code_fixes.length}</span>
                  </div>
                  {report.target_url && (
                    <div className="flex justify-between text-slate-400">
                      <span>Simulated URL:</span>
                      <span className="font-mono text-[10px] text-slate-400 truncate max-w-[150px]">{report.target_url}</span>
                    </div>
                  )}
                </div>
              </div>

              <button
                onClick={() => handleViewReport(report.id)}
                className="mt-6 w-full flex items-center justify-center gap-1.5 text-xs font-semibold border border-indigo-500/20 bg-indigo-600/5 hover:bg-indigo-600/10 text-indigo-400 py-2.5 rounded-xl transition-all"
              >
                Review Fix Suggestions <ArrowRight className="h-3.5 w-3.5" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
